### PR TITLE
Make Date & DateTime culture-insensitive

### PR DESCRIPTION
**Pull request by patrickratzow**
When using ToString() on a Date/DateTime it would use the local culture, resulting in invalid ISO8601 timestamps. Space API will reject the invalid timestamp, and reply 400 Bad Request.

As an example, if the culture was `en-DK`, it would end up with a string looking like `2021-07-22T08.27.15.055Z`, and that's an invalid ISO8601 timestamp as ISO8601 requires `hh:mm:ss` not `hh.mm.ss`.

### CODE REVIEW

**Comment by maartenba** [comment]
Thanks @PatrickRatzow, that's a really good suggestion! I will merge in a bit, and then publish a new release afterwards.

Out of curiosity, what are you building with the SDK?

**Comment by patrickratzow** [comment]
I'm building a small application that'll send meeting reminders to participants shortly before the meeting starts. Right now some people are occasionally late due to being busy, and not looking at the time. A reminder will hopefully help with that.

It's why I specifically noticed the timestamp issue. When I called `MeetingClient.GetAllMeetingsAsync()` it worked fine, but as soon as I added `endingAfter: DateTime.UtcNow` it started throwing exceptions.

**Comment by maartenba** [comment]
That makes sense, thanks!

Manually merged in https://github.com/JetBrains/space-dotnet-sdk/commit/ecad24f4d6fe2e808c5d80d8e8aa70a04dad56a2 , and an update has been pushed to NuGet.

**Comment by maartenba** [comment]
Regarding meeting reminders, feel free to upvote https://youtrack.jetbrains.com/issue/SPACE-6300 which aims to do this out of the box.

(and if you happen to have other Space and/or SDK feedback, happy to chat!)

**Pull request closed without merging**
